// Code generated by tools/generator DO NOT EDIT.
package v1

import (
	"context"
	"fmt"
	"net/http"
)

type TypedClient struct {
	cwr ClientWithResponses
}

// NewTypedClient creates a new TypedClient, which wraps
// Client with return type handling
func NewTypedClient(server string, opts ...ClientOption) (*TypedClient, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	clientWithResponses := &ClientWithResponses{client}
	return &TypedClient{cwr: *clientWithResponses}, nil
}

func (c *TypedClient) ListPostgreSQLs(ctx context.Context, orgId string, projectId string) ([]PostgreSQLGetResponseV1, error) {
	resp, err := c.cwr.ListPostgreSQLsWithResponse(ctx, orgId, projectId)
	if err != nil {
		return nil, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusOK {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return nil, err
	}
	return *resp.JSON200, nil
}

func (c *TypedClient) CreatePostgreSQL(ctx context.Context, orgId string, projectId string, postgreSQLCreateRequestV1 PostgreSQLCreateRequestV1) (PostgreSQLGetResponseV1, error) {
	resp, err := c.cwr.CreatePostgreSQLWithResponse(ctx, orgId, projectId, postgreSQLCreateRequestV1)
	if err != nil {
		return PostgreSQLGetResponseV1{}, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusAccepted {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return PostgreSQLGetResponseV1{}, err
	}
	return *resp.JSON202, nil
}

func (c *TypedClient) UpdatePostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, postgreSQLUpdateRequestV1 PostgreSQLUpdateRequestV1) (PostgreSQLGetResponseV1, error) {
	resp, err := c.cwr.UpdatePostgreSQLWithResponse(ctx, orgId, projectId, dbUuid, postgreSQLUpdateRequestV1)
	if err != nil {
		return PostgreSQLGetResponseV1{}, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusOK {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return PostgreSQLGetResponseV1{}, err
	}
	return *resp.JSON200, nil
}

func (c *TypedClient) DeletePostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string) (APIError, error) {
	resp, err := c.cwr.DeletePostgreSQLWithResponse(ctx, orgId, projectId, dbUuid)
	if err != nil {
		return APIError{}, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusAccepted {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return APIError{}, err
	}
	return *resp.JSON202, nil
}

func (c *TypedClient) GetPostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string) (PostgreSQLGetResponseV1, error) {
	resp, err := c.cwr.GetPostgreSQLWithResponse(ctx, orgId, projectId, dbUuid)
	if err != nil {
		return PostgreSQLGetResponseV1{}, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusOK {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return PostgreSQLGetResponseV1{}, err
	}
	return *resp.JSON200, nil
}

func (c *TypedClient) PatchPostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, postgreSQLPatchRequest PostgreSQLPatchRequest) (PostgreSQLGetResponseV1, error) {
	resp, err := c.cwr.PatchPostgreSQLWithResponse(ctx, orgId, projectId, dbUuid, postgreSQLPatchRequest)
	if err != nil {
		return PostgreSQLGetResponseV1{}, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusOK {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return PostgreSQLGetResponseV1{}, err
	}
	return *resp.JSON200, nil
}

func (c *TypedClient) ListPostgreSQLFlavors(ctx context.Context, orgId string, projectId string) ([]Flavor, error) {
	resp, err := c.cwr.ListPostgreSQLFlavorsWithResponse(ctx, orgId, projectId)
	if err != nil {
		return nil, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusOK {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return nil, err
	}
	return *resp.JSON200, nil
}

func (c *TypedClient) ListPostgreSQLRegions(ctx context.Context, orgId string, projectId string) ([]Region, error) {
	resp, err := c.cwr.ListPostgreSQLRegionsWithResponse(ctx, orgId, projectId)
	if err != nil {
		return nil, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusOK {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return nil, err
	}
	return *resp.JSON200, nil
}

func (c *TypedClient) ListPostgreSQLVersions(ctx context.Context, orgId string, projectId string) ([]Version, error) {
	resp, err := c.cwr.ListPostgreSQLVersionsWithResponse(ctx, orgId, projectId)
	if err != nil {
		return nil, fmt.Errorf("failed to invoke request: %w", err)
	}
	if resp.StatusCode() != http.StatusOK {
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		return nil, err
	}
	return *resp.JSON200, nil
}
