// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	EntityHeaderScopes = "EntityHeader.Scopes"
	StaticAuthScopes   = "StaticAuth.Scopes"
)

// APIError defines model for APIError.
type APIError struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Code HTTP status code
	Code int64 `json:"code"`

	// Msg Error message
	Msg string `json:"msg"`

	// Status HTTP status
	Status string `json:"status"`
}

// Flavor defines model for Flavor.
type Flavor struct {
	Default     bool   `json:"default"`
	Description string `json:"description"`
	Id          string `json:"id"`
}

// PostgreSQLApplicationConfigV1 defines model for PostgreSQLApplicationConfigV1.
type PostgreSQLApplicationConfigV1 struct {
	Hostname         *string                   `json:"hostname,omitempty"`
	Instances        *int64                    `json:"instances"`
	IpAddress        *string                   `json:"ip_address,omitempty"`
	Password         string                    `json:"password"`
	Recovery         *PostgreSQLRecovery       `json:"recovery,omitempty"`
	ScheduledBackups *PostgreSQLBackupSchedule `json:"scheduled_backups,omitempty"`
	Type             string                    `json:"type"`
	Version          string                    `json:"version"`
}

// PostgreSQLBackupSchedule defines model for PostgreSQLBackupSchedule.
type PostgreSQLBackupSchedule struct {
	Retention *int64                          `json:"retention,omitempty"`
	Schedule  *PostgreSQLBackupScheduleConfig `json:"schedule,omitempty"`
}

// PostgreSQLBackupScheduleConfig defines model for PostgreSQLBackupScheduleConfig.
type PostgreSQLBackupScheduleConfig struct {
	Hour   *int64 `json:"hour,omitempty"`
	Minute *int64 `json:"minute,omitempty"`
}

// PostgreSQLCreateRequestV1 defines model for PostgreSQLCreateRequestV1.
type PostgreSQLCreateRequestV1 struct {
	// Schema A URL to the JSON Schema for this object.
	Schema            *string                       `json:"$schema,omitempty"`
	ApplicationConfig PostgreSQLApplicationConfigV1 `json:"application_config"`
	Description       *string                       `json:"description,omitempty"`
	Name              string                        `json:"name"`
	ServiceConfig     PostgreSQLServiceConfigV1     `json:"service_config"`
}

// PostgreSQLGetResponseV1 defines model for PostgreSQLGetResponseV1.
type PostgreSQLGetResponseV1 struct {
	// Schema A URL to the JSON Schema for this object.
	Schema            *string                       `json:"$schema,omitempty"`
	ApplicationConfig PostgreSQLApplicationConfigV1 `json:"application_config"`
	CreatedAt         *time.Time                    `json:"created_at"`
	CreatedBy         string                        `json:"created_by"`
	Description       string                        `json:"description"`
	LastModifiedAt    *time.Time                    `json:"last_modified_at"`
	LastModifiedBy    string                        `json:"last_modified_by"`
	Name              string                        `json:"name"`
	Phase             string                        `json:"phase"`
	ResourceStatus    string                        `json:"resource_status"`
	ServiceConfig     PostgreSQLServiceConfigV1     `json:"service_config"`
	Status            string                        `json:"status"`
	Uuid              string                        `json:"uuid"`
}

// PostgreSQLMaintenance Maintenance window in UTC. This will be a time window for updates and maintenance. If omitted, a random window will be generated.
type PostgreSQLMaintenance struct {
	DayOfWeek   *int64 `json:"day_of_week,omitempty"`
	StartHour   *int64 `json:"start_hour,omitempty"`
	StartMinute *int64 `json:"start_minute,omitempty"`
}

// PostgreSQLPatchRequest defines model for PostgreSQLPatchRequest.
type PostgreSQLPatchRequest struct {
	// Schema A URL to the JSON Schema for this object.
	Schema            *string `json:"$schema,omitempty"`
	ApplicationConfig *struct {
		Hostname          *string `json:"hostname,omitempty"`
		Instances         *int64  `json:"instances,omitempty"`
		IpAddress         *string `json:"ip_address,omitempty"`
		Password          *string `json:"password,omitempty"`
		PrivateNetworking *struct {
			AllowedCidrs     *[]string `json:"allowed_cidrs,omitempty"`
			Enabled          *bool     `json:"enabled,omitempty"`
			Hostname         *string   `json:"hostname,omitempty"`
			IpAddress        *string   `json:"ip_address,omitempty"`
			SharedNetworkId  *string   `json:"shared_network_id,omitempty"`
			SharedSubnetCidr *string   `json:"shared_subnet_cidr,omitempty"`
			SharedSubnetId   *string   `json:"shared_subnet_id,omitempty"`
		} `json:"private_networking,omitempty"`
		PublicNetworking *struct {
			AllowedCidrs *[]string `json:"allowed_cidrs,omitempty"`
			Enabled      *bool     `json:"enabled,omitempty"`
			Hostname     *string   `json:"hostname,omitempty"`
			IpAddress    *string   `json:"ip_address,omitempty"`
		} `json:"public_networking,omitempty"`
		Recovery *struct {
			Exclusive  *bool      `json:"exclusive,omitempty"`
			Source     *string    `json:"source,omitempty"`
			TargetLsn  *string    `json:"target_lsn,omitempty"`
			TargetName *string    `json:"target_name,omitempty"`
			TargetTime *time.Time `json:"target_time,omitempty"`
			TargetXid  *string    `json:"target_xid,omitempty"`
		} `json:"recovery,omitempty"`
		ScheduledBackups *struct {
			Retention *int64 `json:"retention,omitempty"`
			Schedule  *struct {
				Hour   *int64 `json:"hour,omitempty"`
				Minute *int64 `json:"minute,omitempty"`
			} `json:"schedule,omitempty"`
		} `json:"scheduled_backups,omitempty"`
		Type    *string `json:"type,omitempty"`
		Version *string `json:"version,omitempty"`
	} `json:"application_config,omitempty"`
	Description   *string `json:"description,omitempty"`
	Name          *string `json:"name,omitempty"`
	ServiceConfig *struct {
		Disksize *int64  `json:"disksize,omitempty"`
		Flavor   *string `json:"flavor,omitempty"`

		// MaintenanceWindow Maintenance window in UTC. This will be a time window for updates and maintenance. If omitted, a random window will be generated.
		MaintenanceWindow *struct {
			DayOfWeek   *int64 `json:"day_of_week,omitempty"`
			StartHour   *int64 `json:"start_hour,omitempty"`
			StartMinute *int64 `json:"start_minute,omitempty"`
		} `json:"maintenance_window,omitempty"`
		Region    *string   `json:"region,omitempty"`
		RemoteIps *[]string `json:"remote_ips,omitempty"`
		Type      *string   `json:"type,omitempty"`
	} `json:"service_config,omitempty"`
}

// PostgreSQLRecovery defines model for PostgreSQLRecovery.
type PostgreSQLRecovery struct {
	Exclusive  *bool      `json:"exclusive,omitempty"`
	Source     *string    `json:"source,omitempty"`
	TargetLsn  *string    `json:"target_lsn,omitempty"`
	TargetName *string    `json:"target_name,omitempty"`
	TargetTime *time.Time `json:"target_time,omitempty"`
	TargetXid  *string    `json:"target_xid,omitempty"`
}

// PostgreSQLServiceConfigV1 defines model for PostgreSQLServiceConfigV1.
type PostgreSQLServiceConfigV1 struct {
	Disksize *int64 `json:"disksize"`
	Flavor   string `json:"flavor"`

	// MaintenanceWindow Maintenance window in UTC. This will be a time window for updates and maintenance. If omitted, a random window will be generated.
	MaintenanceWindow *PostgreSQLMaintenance `json:"maintenance_window,omitempty"`
	Region            string                 `json:"region"`
	RemoteIps         *[]string              `json:"remote_ips,omitempty"`
	Type              string                 `json:"type"`
}

// PostgreSQLUpdateRequestV1 defines model for PostgreSQLUpdateRequestV1.
type PostgreSQLUpdateRequestV1 struct {
	// Schema A URL to the JSON Schema for this object.
	Schema            *string                       `json:"$schema,omitempty"`
	ApplicationConfig PostgreSQLApplicationConfigV1 `json:"application_config"`
	Description       *string                       `json:"description,omitempty"`
	Name              string                        `json:"name"`
	ServiceConfig     PostgreSQLServiceConfigV1     `json:"service_config"`
}

// Region defines model for Region.
type Region struct {
	Default     bool   `json:"default"`
	Description string `json:"description"`
	Id          string `json:"id"`
}

// Version defines model for Version.
type Version struct {
	Default     bool   `json:"default"`
	Description string `json:"description"`
	Id          string `json:"id"`
}

// CreatePostgreSQLJSONRequestBody defines body for CreatePostgreSQL for application/json ContentType.
type CreatePostgreSQLJSONRequestBody = PostgreSQLCreateRequestV1

// PatchPostgreSQLJSONRequestBody defines body for PatchPostgreSQL for application/json ContentType.
type PatchPostgreSQLJSONRequestBody = PostgreSQLPatchRequest

// UpdatePostgreSQLJSONRequestBody defines body for UpdatePostgreSQL for application/json ContentType.
type UpdatePostgreSQLJSONRequestBody = PostgreSQLUpdateRequestV1

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListPostgreSQLs request
	ListPostgreSQLs(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePostgreSQLWithBody request with any body
	CreatePostgreSQLWithBody(ctx context.Context, orgId string, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePostgreSQL(ctx context.Context, orgId string, projectId string, body CreatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePostgreSQL request
	DeletePostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPostgreSQL request
	GetPostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchPostgreSQLWithBody request with any body
	PatchPostgreSQLWithBody(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchPostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, body PatchPostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdatePostgreSQLWithBody request with any body
	UpdatePostgreSQLWithBody(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdatePostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, body UpdatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPostgreSQLFlavors request
	ListPostgreSQLFlavors(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPostgreSQLRegions request
	ListPostgreSQLRegions(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPostgreSQLVersions request
	ListPostgreSQLVersions(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListPostgreSQLs(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPostgreSQLsRequest(c.Server, orgId, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePostgreSQLWithBody(ctx context.Context, orgId string, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePostgreSQLRequestWithBody(c.Server, orgId, projectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePostgreSQL(ctx context.Context, orgId string, projectId string, body CreatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePostgreSQLRequest(c.Server, orgId, projectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeletePostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePostgreSQLRequest(c.Server, orgId, projectId, dbUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPostgreSQLRequest(c.Server, orgId, projectId, dbUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchPostgreSQLWithBody(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchPostgreSQLRequestWithBody(c.Server, orgId, projectId, dbUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchPostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, body PatchPostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchPostgreSQLRequest(c.Server, orgId, projectId, dbUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdatePostgreSQLWithBody(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePostgreSQLRequestWithBody(c.Server, orgId, projectId, dbUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdatePostgreSQL(ctx context.Context, orgId string, projectId string, dbUuid string, body UpdatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePostgreSQLRequest(c.Server, orgId, projectId, dbUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPostgreSQLFlavors(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPostgreSQLFlavorsRequest(c.Server, orgId, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPostgreSQLRegions(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPostgreSQLRegionsRequest(c.Server, orgId, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPostgreSQLVersions(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPostgreSQLVersionsRequest(c.Server, orgId, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPostgreSQLsRequest generates requests for ListPostgreSQLs
func NewListPostgreSQLsRequest(server string, orgId string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/databases", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePostgreSQLRequest calls the generic CreatePostgreSQL builder with application/json body
func NewCreatePostgreSQLRequest(server string, orgId string, projectId string, body CreatePostgreSQLJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePostgreSQLRequestWithBody(server, orgId, projectId, "application/json", bodyReader)
}

// NewCreatePostgreSQLRequestWithBody generates requests for CreatePostgreSQL with any type of body
func NewCreatePostgreSQLRequestWithBody(server string, orgId string, projectId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/databases", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeletePostgreSQLRequest generates requests for DeletePostgreSQL
func NewDeletePostgreSQLRequest(server string, orgId string, projectId string, dbUuid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "db_uuid", dbUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/databases/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPostgreSQLRequest generates requests for GetPostgreSQL
func NewGetPostgreSQLRequest(server string, orgId string, projectId string, dbUuid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "db_uuid", dbUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/databases/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchPostgreSQLRequest calls the generic PatchPostgreSQL builder with application/json body
func NewPatchPostgreSQLRequest(server string, orgId string, projectId string, dbUuid string, body PatchPostgreSQLJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchPostgreSQLRequestWithBody(server, orgId, projectId, dbUuid, "application/json", bodyReader)
}

// NewPatchPostgreSQLRequestWithBody generates requests for PatchPostgreSQL with any type of body
func NewPatchPostgreSQLRequestWithBody(server string, orgId string, projectId string, dbUuid string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "db_uuid", dbUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/databases/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdatePostgreSQLRequest calls the generic UpdatePostgreSQL builder with application/json body
func NewUpdatePostgreSQLRequest(server string, orgId string, projectId string, dbUuid string, body UpdatePostgreSQLJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdatePostgreSQLRequestWithBody(server, orgId, projectId, dbUuid, "application/json", bodyReader)
}

// NewUpdatePostgreSQLRequestWithBody generates requests for UpdatePostgreSQL with any type of body
func NewUpdatePostgreSQLRequestWithBody(server string, orgId string, projectId string, dbUuid string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "db_uuid", dbUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/databases/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPostgreSQLFlavorsRequest generates requests for ListPostgreSQLFlavors
func NewListPostgreSQLFlavorsRequest(server string, orgId string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/options/databases/postgresql/flavors", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListPostgreSQLRegionsRequest generates requests for ListPostgreSQLRegions
func NewListPostgreSQLRegionsRequest(server string, orgId string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/options/databases/postgresql/regions", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListPostgreSQLVersionsRequest generates requests for ListPostgreSQLVersions
func NewListPostgreSQLVersionsRequest(server string, orgId string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "project_id", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/v1/options/databases/postgresql/versions", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListPostgreSQLsWithResponse request
	ListPostgreSQLsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLsResponse, error)

	// CreatePostgreSQLWithBodyWithResponse request with any body
	CreatePostgreSQLWithBodyWithResponse(ctx context.Context, orgId string, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePostgreSQLResponse, error)

	CreatePostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, body CreatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePostgreSQLResponse, error)

	// DeletePostgreSQLWithResponse request
	DeletePostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*DeletePostgreSQLResponse, error)

	// GetPostgreSQLWithResponse request
	GetPostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*GetPostgreSQLResponse, error)

	// PatchPostgreSQLWithBodyWithResponse request with any body
	PatchPostgreSQLWithBodyWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchPostgreSQLResponse, error)

	PatchPostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, body PatchPostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchPostgreSQLResponse, error)

	// UpdatePostgreSQLWithBodyWithResponse request with any body
	UpdatePostgreSQLWithBodyWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePostgreSQLResponse, error)

	UpdatePostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, body UpdatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePostgreSQLResponse, error)

	// ListPostgreSQLFlavorsWithResponse request
	ListPostgreSQLFlavorsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLFlavorsResponse, error)

	// ListPostgreSQLRegionsWithResponse request
	ListPostgreSQLRegionsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLRegionsResponse, error)

	// ListPostgreSQLVersionsWithResponse request
	ListPostgreSQLVersionsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLVersionsResponse, error)
}

type ListPostgreSQLsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PostgreSQLGetResponseV1
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON501 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r ListPostgreSQLsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPostgreSQLsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreatePostgreSQLResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *PostgreSQLGetResponseV1
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON422 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON501 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON502 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON504 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r CreatePostgreSQLResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePostgreSQLResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeletePostgreSQLResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *APIError
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON404 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON501 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON502 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON504 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r DeletePostgreSQLResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePostgreSQLResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPostgreSQLResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostgreSQLGetResponseV1
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON404 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON501 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r GetPostgreSQLResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPostgreSQLResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchPostgreSQLResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostgreSQLGetResponseV1
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON404 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON422 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON501 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON502 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON504 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r PatchPostgreSQLResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchPostgreSQLResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdatePostgreSQLResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PostgreSQLGetResponseV1
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON404 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON422 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON501 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON502 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON504 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r UpdatePostgreSQLResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdatePostgreSQLResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListPostgreSQLFlavorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Flavor
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r ListPostgreSQLFlavorsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPostgreSQLFlavorsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListPostgreSQLRegionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Region
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r ListPostgreSQLRegionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPostgreSQLRegionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListPostgreSQLVersionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Version
	JSON400      *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON401 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON403 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON500 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
	JSON503 *struct {
		// Code HTTP status code
		Code int64 `json:"code"`

		// Msg Error message
		Msg string `json:"msg"`

		// Status HTTP status
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r ListPostgreSQLVersionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPostgreSQLVersionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListPostgreSQLsWithResponse request returning *ListPostgreSQLsResponse
func (c *ClientWithResponses) ListPostgreSQLsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLsResponse, error) {
	rsp, err := c.ListPostgreSQLs(ctx, orgId, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPostgreSQLsResponse(rsp)
}

// CreatePostgreSQLWithBodyWithResponse request with arbitrary body returning *CreatePostgreSQLResponse
func (c *ClientWithResponses) CreatePostgreSQLWithBodyWithResponse(ctx context.Context, orgId string, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePostgreSQLResponse, error) {
	rsp, err := c.CreatePostgreSQLWithBody(ctx, orgId, projectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePostgreSQLResponse(rsp)
}

func (c *ClientWithResponses) CreatePostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, body CreatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePostgreSQLResponse, error) {
	rsp, err := c.CreatePostgreSQL(ctx, orgId, projectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePostgreSQLResponse(rsp)
}

// DeletePostgreSQLWithResponse request returning *DeletePostgreSQLResponse
func (c *ClientWithResponses) DeletePostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*DeletePostgreSQLResponse, error) {
	rsp, err := c.DeletePostgreSQL(ctx, orgId, projectId, dbUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePostgreSQLResponse(rsp)
}

// GetPostgreSQLWithResponse request returning *GetPostgreSQLResponse
func (c *ClientWithResponses) GetPostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, reqEditors ...RequestEditorFn) (*GetPostgreSQLResponse, error) {
	rsp, err := c.GetPostgreSQL(ctx, orgId, projectId, dbUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPostgreSQLResponse(rsp)
}

// PatchPostgreSQLWithBodyWithResponse request with arbitrary body returning *PatchPostgreSQLResponse
func (c *ClientWithResponses) PatchPostgreSQLWithBodyWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchPostgreSQLResponse, error) {
	rsp, err := c.PatchPostgreSQLWithBody(ctx, orgId, projectId, dbUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchPostgreSQLResponse(rsp)
}

func (c *ClientWithResponses) PatchPostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, body PatchPostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchPostgreSQLResponse, error) {
	rsp, err := c.PatchPostgreSQL(ctx, orgId, projectId, dbUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchPostgreSQLResponse(rsp)
}

// UpdatePostgreSQLWithBodyWithResponse request with arbitrary body returning *UpdatePostgreSQLResponse
func (c *ClientWithResponses) UpdatePostgreSQLWithBodyWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePostgreSQLResponse, error) {
	rsp, err := c.UpdatePostgreSQLWithBody(ctx, orgId, projectId, dbUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePostgreSQLResponse(rsp)
}

func (c *ClientWithResponses) UpdatePostgreSQLWithResponse(ctx context.Context, orgId string, projectId string, dbUuid string, body UpdatePostgreSQLJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePostgreSQLResponse, error) {
	rsp, err := c.UpdatePostgreSQL(ctx, orgId, projectId, dbUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePostgreSQLResponse(rsp)
}

// ListPostgreSQLFlavorsWithResponse request returning *ListPostgreSQLFlavorsResponse
func (c *ClientWithResponses) ListPostgreSQLFlavorsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLFlavorsResponse, error) {
	rsp, err := c.ListPostgreSQLFlavors(ctx, orgId, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPostgreSQLFlavorsResponse(rsp)
}

// ListPostgreSQLRegionsWithResponse request returning *ListPostgreSQLRegionsResponse
func (c *ClientWithResponses) ListPostgreSQLRegionsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLRegionsResponse, error) {
	rsp, err := c.ListPostgreSQLRegions(ctx, orgId, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPostgreSQLRegionsResponse(rsp)
}

// ListPostgreSQLVersionsWithResponse request returning *ListPostgreSQLVersionsResponse
func (c *ClientWithResponses) ListPostgreSQLVersionsWithResponse(ctx context.Context, orgId string, projectId string, reqEditors ...RequestEditorFn) (*ListPostgreSQLVersionsResponse, error) {
	rsp, err := c.ListPostgreSQLVersions(ctx, orgId, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPostgreSQLVersionsResponse(rsp)
}

// ParseListPostgreSQLsResponse parses an HTTP response from a ListPostgreSQLsWithResponse call
func ParseListPostgreSQLsResponse(rsp *http.Response) (*ListPostgreSQLsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPostgreSQLsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PostgreSQLGetResponseV1
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseCreatePostgreSQLResponse parses an HTTP response from a CreatePostgreSQLWithResponse call
func ParseCreatePostgreSQLResponse(rsp *http.Response) (*CreatePostgreSQLResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePostgreSQLResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest PostgreSQLGetResponseV1
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseDeletePostgreSQLResponse parses an HTTP response from a DeletePostgreSQLWithResponse call
func ParseDeletePostgreSQLResponse(rsp *http.Response) (*DeletePostgreSQLResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePostgreSQLResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseGetPostgreSQLResponse parses an HTTP response from a GetPostgreSQLWithResponse call
func ParseGetPostgreSQLResponse(rsp *http.Response) (*GetPostgreSQLResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPostgreSQLResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostgreSQLGetResponseV1
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParsePatchPostgreSQLResponse parses an HTTP response from a PatchPostgreSQLWithResponse call
func ParsePatchPostgreSQLResponse(rsp *http.Response) (*PatchPostgreSQLResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchPostgreSQLResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostgreSQLGetResponseV1
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseUpdatePostgreSQLResponse parses an HTTP response from a UpdatePostgreSQLWithResponse call
func ParseUpdatePostgreSQLResponse(rsp *http.Response) (*UpdatePostgreSQLResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdatePostgreSQLResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PostgreSQLGetResponseV1
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseListPostgreSQLFlavorsResponse parses an HTTP response from a ListPostgreSQLFlavorsWithResponse call
func ParseListPostgreSQLFlavorsResponse(rsp *http.Response) (*ListPostgreSQLFlavorsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPostgreSQLFlavorsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Flavor
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListPostgreSQLRegionsResponse parses an HTTP response from a ListPostgreSQLRegionsWithResponse call
func ParseListPostgreSQLRegionsResponse(rsp *http.Response) (*ListPostgreSQLRegionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPostgreSQLRegionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Region
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListPostgreSQLVersionsResponse parses an HTTP response from a ListPostgreSQLVersionsWithResponse call
func ParseListPostgreSQLVersionsResponse(rsp *http.Response) (*ListPostgreSQLVersionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPostgreSQLVersionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Version
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP status code
			Code int64 `json:"code"`

			// Msg Error message
			Msg string `json:"msg"`

			// Status HTTP status
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
