package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"slices"
	"sort"
	"strings"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
)

var templateSource = `
// Code generated by tools/generator DO NOT EDIT.
package {{ .Package }}

import (
{{- range .Imports}}
	"{{ . }}"
{{- end}}
)

type TypedClient struct {
	cwr ClientWithResponses
}

// NewTypedClient creates a new TypedClient, which wraps
// Client with return type handling
func NewTypedClient(server string, opts ...ClientOption) (*TypedClient, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	clientWithResponses := &ClientWithResponses{client}
	return &TypedClient{cwr: *clientWithResponses}, nil
}

{{range .Functions}}
func (c *TypedClient) {{ .Name }}(ctx context.Context{{ range .Arguments }}, {{.Qualifier}} {{.Type}}{{end}}) ({{ if .Return.List }}[]{{ end }}{{ .Return.Type }}, error) {
	resp, err := c.cwr.{{ .Name }}WithResponse(ctx{{ range .Arguments }}, {{.Qualifier}}{{end}})
	if err != nil {
		{{- if .Return.List }}
			return nil, fmt.Errorf("failed to invoke request: %w", err)
		{{- else }}
			return {{ .Return.Type }}{}, fmt.Errorf("failed to invoke request: %w", err)
		{{- end }}
	}

	{{- if eq .Method "POST" }}
	if resp.StatusCode() != http.StatusAccepted {
	{{- else if eq .Method "DELETE" }}
	if resp.StatusCode() != http.StatusAccepted {
	{{- else }}
	if resp.StatusCode() != http.StatusOK {
	{{- end }}
		err := fmt.Errorf("got invalid response: %s: %s", resp.Status(), string(resp.Body))
		{{- if .Return.List }}
		return nil, err
		{{- else }}
		return {{ .Return.Type }}{}, err
		{{- end }}
	}

	{{- if eq .Method "POST" }}
	return *resp.JSON202, nil
	{{- else if eq .Method "DELETE" }}
	return *resp.JSON202, nil
	{{- else }}
	return *resp.JSON200, nil
	{{- end }}
}
{{ end }}
`

func main() {
	if err := execute(); err != nil {
		slog.Error("failed to execute", "error", err)
		os.Exit(1)
	}
}

func execute() error {
	if len(os.Args) < 4 {
		fmt.Printf("missing arguments")
	}

	packageName := os.Args[3]
	tag := os.Args[4]

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, uri *url.URL) ([]byte, error) {
		return os.ReadFile(uri.Path)
	}

	doc, err := loader.LoadFromFile(os.Args[1])
	if err != nil {
		return fmt.Errorf("failed to load openapi spec: %w", err)
	}

	codegen.SetGlobalStateSpec(doc)

	type ReturnType struct {
		Type string
		List bool
	}

	type Argument struct {
		Qualifier string
		Type      string
	}

	type Function struct {
		Name      string
		Arguments []Argument
		Return    ReturnType
		Method    string
	}

	data := &struct {
		Package   string
		Imports   []string
		Functions []Function
	}{
		Package: packageName,
		Imports: []string{
			"context",
			"net/http",
			"fmt",
		},
		Functions: []Function{},
	}

	paths := doc.Paths

	keys := make([]string, 0, paths.Len())
	for key := range paths.Map() {
		keys = append(keys, key)
	}

	sort.Strings(keys)
	for _, path := range keys {
		pathItem := paths.Value(path)
		if path == "" || path[0] != '/' {
			return fmt.Errorf("path %q does not start with a forward slash (/)", path)
		}

		for method, op := range pathItem.Operations() {
			if !slices.Contains(op.Tags, tag) {
				continue
			}
			arguments := []Argument{}
			for _, parameter := range op.Parameters {
				arguments = append(arguments, Argument{
					Qualifier: codegen.LowercaseFirstCharacter(codegen.ToCamelCaseWithInitialisms(parameter.Value.Name)),
					Type:      parameter.Value.Schema.Value.Type.Slice()[0],
				})
			}

			if op.RequestBody != nil {
				content := op.RequestBody.Value.Content.Get("application/json")

				typ := ""
				if content.Schema.Ref != "" {
					refElements := strings.Split(content.Schema.Ref, "/")
					typ = refElements[len(refElements)-1]
				}

				arguments = append(arguments, Argument{
					Qualifier: codegen.LowercaseFirstCharacter(typ),
					Type:      typ,
				})
			}

			response := op.Responses.Status(http.StatusOK)
			if method == http.MethodPost || method == http.MethodDelete {
				response = op.Responses.Status(http.StatusAccepted)
			}
			if response == nil {
				continue
			}
			content := response.Value.Content.Get("application/json")

			operationId := op.OperationID
			if operationId == "" {
				operationId = generateFunctionName(method, path)
			}

			typ := ""
			if content.Schema.Ref != "" {
				refElements := strings.Split(content.Schema.Ref, "/")
				typ = refElements[len(refElements)-1]

			}
			if content.Schema.Value.Type.Is("array") {
				refElements := strings.Split(content.Schema.Value.Items.Ref, "/")
				typ = refElements[len(refElements)-1]
			}

			data.Functions = append(data.Functions, Function{
				Name:      operationId,
				Arguments: arguments,
				Method:    method,
				Return: ReturnType{
					Type: typ,
					List: content.Schema.Value.Type.Is("array"),
				},
			})
		}
	}

	tmpl := template.Must(template.New("src").Parse(templateSource))
	var buffer bytes.Buffer
	if err := tmpl.Execute(&buffer, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated sources: %w", err)
	}

	filename := os.Args[2]

	if err := os.WriteFile(filename, formatted, 0o644); err != nil {
		return fmt.Errorf("failed to write generated file: %w", err)
	}

	return nil
}

func generateFunctionName(method string, path string) string {
	pathElements := strings.Split(path, "/")

	name := strings.ToLower(method)
	for _, pathElement := range pathElements {
		pathElement = strings.ReplaceAll(pathElement, "{", "")
		pathElement = strings.ReplaceAll(pathElement, "}", "")
		name += "-" + pathElement
	}
	return codegen.ToCamelCaseWithInitialisms(name)
}
